---

#- name: Debug
#  hosts: all
#  tasks:
#    - debug:
#      msg: "{{ ansible_hostname }}"

- name: Basic setup
  hosts: all
  roles:
    - common
    - certificates

- name: etcd
  hosts: etcd
  roles:
    - etcd

# vim: ai expandtab ts=2 sts=2 sw=2
    
