---
# tasks docker debian

- block:
  - name: Install deps
    apt: name={{ item }} state=present
    with_items:
      - apt-transport-https
      - ca-certificates
      - python-pip

  - name: Remove old apt keys
    apt_key:
      id: "{{ item }}"
      state: absent
    with_items:
      - 58118E89F3A912897C070ADBF76221572C52609D

  - name: Remove old apt repo
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo/ {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main
      state: absent
      update_cache: yes
      filename: 'docker'

  - name: Add apt key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg

  - name: Add apt repo
    apt_repository:
      repo: deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_distribution_release }} {{ docker_release_channel }}
      state: present
      update_cache: yes
      filename: 'docker'

  - name: Install
    apt:
      name: docker-ce
      state: present

  - name: Install python components
    pip: 
      name: docker-compose
      state: present

  - name: Ensure systemd config override directory
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: 0755
    when: ansible_service_mgr == 'systemd'

  - name: Configure docker_opts
    template:
      src: docker_exec.conf.j2
      dest: /etc/systemd/system/docker.service.d/docker_exec.conf
      owner: root
      group: root
      mode: 0644
    register: result_docker_opts
    when: ansible_service_mgr == 'systemd'

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    when:
      - result_docker_opts.changed
      - ansible_service_mgr == 'systemd'

  - name: Esure service enabled
    service:
      name: docker
      enabled: yes
      state: started

  become: true

