---
# tasks certificates

- name: Ensure certificates dir
  file:
    path: "{{ certificates_remote_path }}"
    state: directory
    mode: 0750
    owner: root
    group: root
  become: true

- name: Ensure certificates
  copy:
    src: "{{ certificates_path }}/{{ item }}"
    dest: "{{ certificates_remote_path }}/{{ item }}"
    mode: 0640
    owner: root
    group: root
  become: true
  with_items:
    - ca.pem
    - kubernetes.pem
    - kubernetes-key.pem


# vim: ai et sw=2 st=2 sts=2

